project:
  name: quickstart-onica-cci-postcall-analytics
  owner: quickstart-eng@amazon.com
  regions:
    - us-west-2
    - us-east-1
  template: templates/master.template.yaml
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: quickstart-onica-cci-postcall-analytics/
  s3_regional_buckets: true
tests:
  master:
    regions: 
      - us-east-1
    parameters: 
      UserPoolDomainName: icc-domaintost
      